"use client";

import { AnimatePresence, motion, useScroll, useSpring } from "framer-motion";
import { ArrowUpRight, BrainCircuit, Check, ChevronRight, Code2, Download, ExternalLink, Github, Linkedin, Mail, MapPin, Menu, Moon, Phone, Send, Sun, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

const nav = ["Home", "About", "Skills", "Projects", "Experience", "Education", "Certificates", "Achievements", "Contact"];
const skills = [
  ["Programming", ["Java", "Python", "SQL", "JavaScript", "TypeScript"]],
  ["AI & Machine Learning", ["Scikit-Learn", "TensorFlow", "NLTK", "Regression", "Classification", "Sentiment Analysis"]],
  ["Frontend", ["React", "Next.js", "HTML", "CSS", "Tailwind CSS", "Bootstrap"]],
  ["Backend & Data", ["Node.js", "Express.js", "REST API", "MongoDB", "MySQL"]],
];
const projects = [
  { title: "AI-Powered Financial Behavior Analyzer", cat: "AI / Full Stack", image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=85", tech: ["React", "Node.js", "MongoDB", "Gemini AI"], text: "An intelligent finance workspace that turns everyday transactions into clearer, smarter decisions.", features: ["Expense intelligence", "Dashboard analytics", "AI financial advisor"] },
  { title: "Smart Helmet Accident Detection", cat: "IoT", image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85", tech: ["ESP32", "MPU6050", "GPS", "GSM"], text: "An IoT safety system that detects an accident and relays precise location data for faster emergency response.", features: ["Impact detection", "Live GPS alert", "LoRa-ready architecture"] },
  { title: "Emotion-Based Book Recommender", cat: "Machine Learning", image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1200&q=85", tech: ["Python", "NLTK", "Scikit-Learn"], text: "A warm, personal recommendation engine that maps emotional signals to the right next read.", features: ["NLP emotion analysis", "Sentiment model", "Personalized results"] },
  { title: "Library Management System", cat: "Java", image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=85", tech: ["Java", "MySQL"], text: "A dependable desktop system that makes book lending, returns, and catalogue management effortless.", features: ["Book catalogue", "Issue & returns", "Member management"] }
];
const roles = ["AI Engineer", "Machine Learning Developer", "Full Stack Developer", "Java Developer", "IoT Developer"];

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: .55 }}>{children}</motion.div>; }
function SectionHead({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <Reveal className="max-w-2xl mb-12"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{copy && <p className="mt-5 text-slate-600 dark:text-slate-400 leading-7">{copy}</p>}</Reveal>; }

export default function Portfolio() {
  const { scrollYProgress } = useScroll(); const progress = useSpring(scrollYProgress, { stiffness: 110, damping: 24 });
  const [dark, setDark] = useState(true), [menu, setMenu] = useState(false), [role, setRole] = useState(0), [filter, setFilter] = useState("All");
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
  useEffect(() => { const i = setInterval(() => setRole(v => (v + 1) % roles.length), 2400); return () => clearInterval(i); }, []);
  const shown = filter === "All" ? projects : projects.filter(p => p.cat === filter);
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); alert("Thanks for reaching out — your message is ready to send."); e.currentTarget.reset(); };
  return <main className="bg-[#f8fafc] text-ink dark:bg-[#0b1224] dark:text-slate-100 transition-colors duration-300 overflow-hidden">
    <motion.div className="progress" style={{ scaleX: progress }} />
    <header className="fixed inset-x-0 top-0 z-40"><div className="mx-auto mt-4 max-w-6xl px-4"><nav className="nav-shell"><a href="#home" className="logo">K<span>S.</span></a><div className="hidden lg:flex items-center gap-5">{nav.map(x => <a key={x} href={`#${x.toLowerCase()}`} className="nav-link">{x}</a>)}</div><div className="flex items-center gap-2"><button aria-label="Toggle color mode" onClick={() => setDark(!dark)} className="icon-button">{dark ? <Sun size={17}/> : <Moon size={17}/>}</button><button aria-label="Open menu" onClick={() => setMenu(!menu)} className="icon-button lg:hidden">{menu ? <X/> : <Menu/>}</button></div></nav>{menu && <div className="mobile-menu">{nav.map(x => <a onClick={() => setMenu(false)} key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</div>}</div></header>
    <section id="home" className="hero-grid min-h-screen pt-28"><div className="hero-orb orb-1"/><div className="hero-orb orb-2"/><div className="absolute inset-0 dot-grid opacity-40"/><div className="relative z-10 mx-auto max-w-6xl px-6 w-full flex items-center"><div className="max-w-4xl"><motion.div initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.55}}><p className="eyebrow">Hello, I&apos;m Maileeshwar</p><h1 className="hero-title">Engineering ideas into<br/><span>intelligent impact.</span></h1><div className="flex items-center gap-3 text-lg md:text-xl text-slate-600 dark:text-slate-300"><BrainCircuit className="text-cyan"/><AnimatePresence mode="wait"><motion.span key={role} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{roles[role]}</motion.span></AnimatePresence></div><p className="mt-7 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-400">Building AI-powered intelligent solutions that solve real-world problems — from thoughtful interfaces to robust machine learning systems.</p><div className="mt-9 flex flex-wrap gap-3"><a className="button-primary" href="#projects">View my work <ArrowUpRight size={17}/></a><a className="button-secondary" href="mailto:maileeshsrinivasan@gmail.com">Let&apos;s talk <ChevronRight size={17}/></a></div><div className="mt-11 flex gap-5 text-sm text-slate-500 dark:text-slate-400"><a className="social-text" target="_blank" href="https://github.com/maileeshwar"><Github size={17}/> GitHub</a><a className="social-text" target="_blank" href="https://www.linkedin.com/in/maileeshwar-srinivasan-81b68b292/"><Linkedin size={17}/> LinkedIn</a></div></motion.div></div></div><div className="absolute bottom-10 left-1/2 -translate-x-1/2 text-[11px] uppercase tracking-[.22em] text-slate-500">Scroll to explore</div></section>
    <section id="about" className="section"><div className="mx-auto max-w-6xl px-6 grid lg:grid-cols-[1.05fr_.95fr] gap-14 items-center"><SectionHead eyebrow="01 / About" title="Curious by nature. Precise by design." copy="I&apos;m an AI & Data Science Engineer from Tamil Nadu who loves taking a vague, real-world problem and shaping it into a clear, useful product. My work lives at the intersection of machine learning, data, thoughtful software, and practical innovation."/><Reveal className="glass-card p-8 md:p-10"><p className="text-xl leading-8 font-medium">“The best technology feels less like technology — and more like possibility.”</p><div className="mt-8 grid grid-cols-2 gap-4">{["AI & Machine Learning", "Natural Language Processing", "IoT & Automation", "Research & Innovation"].map((x,i) => <div key={x} className="rounded-2xl bg-blue-50 dark:bg-white/[.05] p-4"><span className="text-xs text-cyan">0{i+1}</span><p className="mt-2 text-sm font-semibold">{x}</p></div>)}</div></Reveal></div></section>
    <section id="skills" className="section section-tint"><div className="mx-auto max-w-6xl px-6"><SectionHead eyebrow="02 / Toolkit" title="A practical, evolving technical foundation." copy="The tools I reach for to make data useful, interfaces intuitive, and systems dependable."/><div className="grid md:grid-cols-2 gap-5">{skills.map(([group, items], idx) => <Reveal key={String(group)} className="skill-card"><div className="flex justify-between"><h3>{group}</h3><span className="text-cyan text-sm">0{idx+1}</span></div><div className="mt-5 flex flex-wrap gap-2">{(items as string[]).map((s,i) => <span className="chip" key={s}>{s}<i style={{width:`${65 + (i*7)%31}%`}}/></span>)}</div></Reveal>)}</div></div></section>
    <section id="projects" className="section"><div className="mx-auto max-w-6xl px-6"><SectionHead eyebrow="03 / Selected work" title="Built with curiosity. Grounded in impact."/><div className="flex flex-wrap gap-2 mb-8">{["All", "AI / Full Stack", "IoT", "Machine Learning", "Java"].map(x => <button onClick={() => setFilter(x)} className={`filter ${filter===x?"active":""}`} key={x}>{x}</button>)}</div><motion.div layout className="grid md:grid-cols-2 gap-6">{shown.map(p => <motion.article layout key={p.title} className="project-card group"><div className="project-img" style={{backgroundImage:`linear-gradient(180deg,transparent 45%,rgba(4,11,30,.78)),url('${p.image}')`}}><span>{p.cat}</span></div><div className="p-6"><h3 className="text-xl font-semibold">{p.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-400">{p.text}</p><div className="mt-4 flex flex-wrap gap-2">{p.tech.map(t => <b className="tech" key={t}>{t}</b>)}</div><div className="mt-5 flex gap-4"><a href="https://github.com/maileeshwar" target="_blank" className="project-link"><Github size={16}/> Code</a><a href="#contact" className="project-link">Details <ArrowUpRight size={16}/></a></div></div></motion.article>)}</motion.div></div></section>
    <section id="experience" className="section section-tint"><div className="mx-auto max-w-6xl px-6"><SectionHead eyebrow="04 / Experience" title="Learning by shipping."/><div className="timeline"><Reveal className="timeline-item"><p className="eyebrow">Data Science Intern</p><h3>Training Trains</h3><p>Built a hands-on data science practice through data cleaning, preprocessing, visualisation, EDA, web scraping, and machine learning workflows.</p></Reveal><Reveal className="timeline-item"><p className="eyebrow">AI & Data Science Intern</p><h3>F5 Coders</h3><p>Developed Python-based prediction models with NumPy, Pandas, regression, classification, and applied machine learning.</p></Reveal></div></div></section>
    <section id="education" className="section"><div className="mx-auto max-w-6xl px-6"><SectionHead eyebrow="05 / Foundation" title="Grounded in systems thinking."/><Reveal className="glass-card p-8 grid md:grid-cols-[1fr_auto] gap-6 items-end"><div><p className="eyebrow">Bachelor of Technology</p><h3 className="text-2xl font-semibold">Artificial Intelligence and Data Science</h3><p className="mt-3 text-slate-600 dark:text-slate-400">Nandha Engineering College</p></div><div className="text-right"><b className="text-4xl text-brand">8.5</b><p className="text-xs tracking-widest uppercase text-slate-500">CGPA</p></div></Reveal></div></section>
    <section id="certificates" className="section section-tint"><div className="mx-auto max-w-6xl px-6"><SectionHead eyebrow="06 / Credentials" title="Always in learning mode."/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{["Python Workshop — IIT Madras", "Tableau Data Visualization", "LeetCode", "HackerRank"].map((x,i) => <Reveal className="credential" key={x}><Code2/><span>0{i+1}</span><p>{x}</p></Reveal>)}</div></div></section>
    <section id="achievements" className="section"><div className="mx-auto max-w-6xl px-6"><SectionHead eyebrow="07 / Milestones" title="A little friendly competition."/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{["Winner — Sound Streams", "BrainBots Participant", "Active LeetCode Solver", "Active HackerRank Coder"].map((x,i) => <Reveal className="stat" key={x}><b>0{i+1}</b><p>{x}</p></Reveal>)}</div></div></section>
    <section id="contact" className="section pb-24"><div className="mx-auto max-w-6xl px-6"><div className="contact-shell"><div><p className="eyebrow">08 / Contact</p><h2 className="section-title">Let&apos;s make something <span>meaningful.</span></h2><p className="mt-5 max-w-md text-slate-600 dark:text-slate-400">Have an ambitious idea, a tough dataset, or an interesting opportunity? I&apos;d love to hear about it.</p><div className="mt-8 space-y-4 text-sm"><a className="contact-row" href="mailto:maileeshsrinivasan@gmail.com"><Mail size={17}/>maileeshsrinivasan@gmail.com</a><a className="contact-row" href="tel:+919677378984"><Phone size={17}/>+91 9677378984</a><div className="contact-row"><MapPin size={17}/>Tamil Nadu, India</div></div></div><form onSubmit={submit} className="contact-form"><input required placeholder="Your name"/><input required type="email" placeholder="Email address"/><input required placeholder="Subject"/><textarea required placeholder="Tell me about your idea" rows={4}/><button className="button-primary justify-center" type="submit">Send message <Send size={16}/></button></form></div></div></section>
    <footer className="border-t border-slate-200 dark:border-white/10"><div className="mx-auto max-w-6xl px-6 py-7 flex flex-col sm:flex-row gap-4 justify-between text-sm text-slate-500"><p>Designed & Developed by <span className="text-slate-800 dark:text-slate-200">Maileeshwar K S</span></p><p>© {new Date().getFullYear()} · Built with intention</p></div></footer><a href="#home" aria-label="Back to top" className="back-top"><ArrowUpRight size={19}/></a>
  </main>;
}
